### PR TITLE
setting up simple routing and linking between game and landing page

### LINKED ISSUE #12: link between landing page and game page

### PR DESCRIPTION
**Pull request by catmembermona**

### CODE REVIEW

**Comment by Jam52** [comment]
Should we have the '/' route point to the landing page and the '/game' go to the game because we want people to land on the landing page first right?

**Comment by catmembermona** [comment]
> Should we have the '/' route point to the landing page and the '/game' go to the game because we want people to land on the landing page first right?

I think that starting the game first would be a bigger impression as the first thing that appears, but our info is more important. I'll change it.

**Comment by catmembermona** [comment]
changes were made

**Comment by Jam52** [comment]
Looks good!

**Pull request merged**
